export const CHANGE_BANNER = 'CHANGE_BANNER'
export const CHANGE_HOTRECOMMEND = 'CHANGE_HOTRECOMMEND'
export const CHANGE_NEWALBUM = 'CHANGE_NEWALBUM'

export const CHANGE_UP_RANKING = 'CHANGE_UP_RANKING'
export const CHANGE_NEW_RANKING = 'CHANGE_NEW_RANKING'
export const CHANGE_ORIGIN_RANKING = 'CHANGE_ORIGIN_RANKING'